### ISSUE TITLE
Source of the Quran Text

### ISSUE THREAD

**Issue by mukhtharcm** [aqeelshamz/quran#1]
If you don't mind, it'll very helpful if you shared the source of this Quran Text. 
So we can be sure of the authenticity of it.

PS: I am not trying to question you. this Is only just for clarity

**Comment by aqeelshamz** [comment]
No problem. You are right. You can find it here:  https://raw.githubusercontent.com/aqeelshamz/quran/main/lib/quran.dart
Pls let me know.

**Comment by aqeelshamz** [comment]
I found it from here: https://raw.githubusercontent.com/risan/quran-json/master/json/quran/text.json
