### ISSUE TITLE
Method to get Surah's pages numbers

### ISSUE THREAD

**Issue by AliYousef97** [aqeelshamz/quran#10]
Hi, please add a method that give us all the pages numbers for a specific surah.

Thanks.

**Comment by psyonixFx** [comment]
@AliYousef97 adding this code as a pull request will be more efficient.
But there is an issue #8 in the pages data unsolved till now unfortunately that intended to fix (but with wierd approch) soon ISA.

**Comment by aqeelshamz** [comment]
You can make a pull request if you don't mind.

**Comment by AliYousef97** [comment]
> You can make a pull request if you don't mind.

Yes, I will make it this Friday, because I am a little busy right now.

**Comment by AliYousef97** [comment]
> @AliYousef97 adding this code as a pull request will be more efficient. But there is an issue #8 in the pages data unsolved till now unfortunately that intended to fix (but with wierd approch) soon ISA.



> @AliYousef97 adding this code as a pull request will be more efficient. But there is an issue #8 in the pages data unsolved till now unfortunately that intended to fix (but with wierd approch) soon ISA.

Thanks for your efforts, I am planing to make a PR this Friday, ISA.

**Comment by aqeelshamz** [comment]
Added. Jazakallahu khairan ✨
