### ISSUE TITLE
getversesymbol is the opposite

### ISSUE THREAD

**Issue by shahbazqa** [aqeelshamz/quran#11]
Hi, 

thanks for this dependency. I have been utilizing the 1.0.2 version and it was working fine so I chose to update to the latest to see what's new, I was using this for the getversesymbol code for my quran app but the ayah symbols are in the wrong direction, 

for example: 
ayah 60 is looking good
![image](https://user-images.githubusercontent.com/64419960/163729737-251f24c0-5d2c-40f6-98c4-ff3e869a342e.png)

but then 61,62,63,all are opposites: 
![image](https://user-images.githubusercontent.com/64419960/163729779-f614c577-f983-4d4c-a5ed-8c3cf258a87e.png)

The 1.0.2 version did not have this issue, but it did show 60 as 06  but all the rest were fine, please if you could fix this... 

thanks

**Comment by shahbazqa** [comment]
![image](https://user-images.githubusercontent.com/64419960/163729908-31ca3ba8-1b6c-4511-ac02-38dadb786c7c.png)

**Comment by shahbazqa** [comment]
Hi, I also need help in finishing this app, if you could help out that would be awesome and get some ajar for it. 
thanks

**Comment by AbdullahAli1993** [comment]
what font do you use?

**Comment by aqeelshamz** [comment]
Issue fixed.
