### ISSUE TITLE
getVerseEndSymbol issue and add some more feature like English translation

### ISSUE THREAD

**Issue by mubeenkhan246** [aqeelshamz/quran#15]
1. VerseEndSymbol overlap on the verse. 
2. Please add English translation.

My App is waiting for these features  😊

**Comment by aqeelshamz** [comment]
✅English Translation added (Saheeh International).

**Comment by mubeenkhan246** [comment]
thanks a lot.

**Comment by mubeenkhan246** [comment]
Thanks a lot.
