### ISSUE TITLE
Some words do not appear correctly any help?

### ISSUE THREAD

**Issue by Basemshawwa** [aqeelshamz/quran#17]
![WhatsApp Image 2022-12-20 at 1 01 20 PM](https://user-images.githubusercontent.com/45998555/208651963-f30e23ac-e156-4fc2-bc4b-2f07f8380203.jpeg)

![ssas](https://user-images.githubusercontent.com/45998555/208652578-a3c32d7f-1830-4e72-9d13-ba359704f090.png)

**Comment by Basemshawwa** [comment]
any help?

**Comment by Basemshawwa** [comment]
any help?

**Comment by aqeelshamz** [comment]
We have to manually correct those words. Can you make a pull request?

**Comment by aqeelshamz** [comment]
Fixed.
