### ISSUE TITLE
There are a lot of mistakes in the text that needs to be changed 

### ISSUE THREAD

**Issue by Khaled-mohamed-dev** [aqeelshamz/quran#18]
assalamualaikum akhi Aqeel, Thanks for your efforts creating this package, I really appreciate it.

But as I was testing the package I notice many words that are written in a wrong way for example [ ٱلْءَاخِرَةِ , ٱلْءَاخِرِ ,  إِبْرَٰهِۦمَ , وَلَّىٰهُمْ ,  تَرْضَىٰهَا, ], and those are only the errors that I managed to notice, only God knows how many mistakes there are .

I don't know how you got that data, but you should not rely on that source. I advice you to use another source.

And if you don't have time, just tell me and I can create a pull request with a better written text.

**Comment by aqeelshamz** [comment]
Wa alaikumussalam wa rahmathullah,

Jazakallah. Thanks for pointing out those errors. It would be helpful if you can make a pull request.

**Comment by aqeelshamz** [comment]
Fixed. Jazakallah khairan.
