### ISSUE TITLE
Wrong in arabic name of Surah "An naba", id=78

### ISSUE THREAD

**Issue by TripApps** [aqeelshamz/quran#22]
There is a typo in arabic name of surah An nabaa id=78
{
    "id": 78,
    "name": "An Naba",
    "aya": 40,
    "english": "The Great News",
    "place": "Makkah",
    "arabic": "النبإ"
  },
  
  The Correct name is "النبأ"

**Comment by aqeelshamz** [comment]
Jazakallah khairan. Fixed.
