### ISSUE TITLE
Wrong in arabic name of Surah "Al Masad", id=111

### ISSUE THREAD

**Issue by TripApps** [aqeelshamz/quran#23]
The correct Arabic name for surah Al masad is "المسد" not "اللهب"

{
    "id": 111,
    "name": "Al Masad",
    "aya": 5,
    "english": "The Plaited Rope",
    "place": "Makkah",
    "arabic": "اللهب" // should be "المسد"
  },

**Comment by aqeelshamz** [comment]
Fixed. Jazakallah khairan.
