### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by gpcodex** [aqeelshamz/quran#25]
here is the French translation adapted to your application.

[fr_Hamidullah.zip](https://github.com/aqeelshamz/quran/files/12268756/fr_Hamidullah.zip)
[surah_data.zip](https://github.com/aqeelshamz/quran/files/12269081/surah_data.zip)
[quran.zip](https://github.com/aqeelshamz/quran/files/12269082/quran.zip)

**Comment by aqeelshamz** [comment]
Can you make a pull request?

**Comment by gpcodex** [comment]
done

**Comment by aqeelshamz** [comment]
Jazakallah khairan
