### ISSUE TITLE
Double digit VerseEndSymbol is incorrect

### ISSUE THREAD

**Issue by shahbazqa** [aqeelshamz/quran#3]
Hi, 

Thank you for creating this. I just have one issue, 
I am using getVerseEndSymbol(12) by itself, 
but when I insert this I am getting 21 
![image](https://user-images.githubusercontent.com/64419960/125472429-4d4a7146-0a70-4cc2-b7ed-9bc844f59ddb.png)

when I change it to getVerseEndSymbol(21)
that's when I am getting = 12 
![image](https://user-images.githubusercontent.com/64419960/125472200-8cbaef04-bcf9-401d-b935-9d5513b9f048.png)

Can this be fixed? 
I am using version 1.0.2 since i don't have null safety.
 

thanks

**Comment by aqeelshamz** [comment]
Try using the default system font for the verse end symbol. Btw, which platform are you working on?

**Comment by shahbazqa** [comment]
I have already started on the Project and implementing ayahs so I guess the work around will do as long as you guys don’t change it . Otherwise I would have to go within 868 classes and change all ayah numbers  from endverseayah(21) = 12 to endverseayah(12) = 21 
I am utilizing flutter on both iOS and Android .

Thanks for this package.
