### ISSUE TITLE
Source of the Quran Text | 2

### ISSUE THREAD

**Issue by Kiura** [aqeelshamz/quran#31]
Assalamu 1aleykum,
I always like any initiatives to increase knowledge and spread islam, so thank you for your efforts, and may Allah reward you!

In the world of lies and disinformation, knowing the sources is a must, especially about Islamic texts. 
Please consider adding it to the home page, so people can do their research and start using your library as soon as they land on the "homepage" of the library.

**Comment by aqeelshamz** [comment]
Wa alaikumussalam wa rahmathullah,

Source: https://raw.githubusercontent.com/risan/quran-json/master/json/quran/text.json
