### ISSUE TITLE
Some words do not appear correctly any help? 

### ISSUE THREAD

**Issue by husen-hn** [aqeelshamz/quran#36]
for example chapter 109 verse 4 you can see % on عابد word

![2024-01-05-130823_1366x768_scrot](https://github.com/aqeelshamz/quran/assets/34922619/3ce4c565-a247-471e-bf40-1e0c638e9204)

**Comment by aqeelshamz** [comment]
There appears to be a font-related problem. Please utilize fonts such as "Uthmanic Hafs Font" or other similar fonts in place of "Amiri Quran".

**Comment by husen-hn** [comment]
> There appears to be a font-related problem. Please utilize fonts such as "Uthmanic Hafs Font" or other similar fonts in place of "Amiri Quran".

It should be mentioned in the document which fonts it is compatible with and Amiri font is a standard font and there should not be such a problem for it.
