### ISSUE TITLE
the symbol

### ISSUE THREAD

**Issue by Romm01** [aqeelshamz/quran#37]
salamu alaykum, 
thank you for this package , verser useful.

but when I make the ( verseEndSymbol ) true, this will happen .

![Uploading issue.png…]()

**Comment by okursoftware** [comment]
The problem only seems to exist on iOS

**Comment by Abdulvaliy** [comment]
I have found that wrong arabic letter codeUnit is used. Just changing arabicNumbers const will solve the problem. We will look for authors action to change that code.

`  const Map arabicNumbers = {
    "0": "٠",
    "1": "١",
    "2": "٢",
    "3": "٣",
    "4": "٤",
    "5": "٥",
    "6": "٦",
    "7": "٧",
    "8": "٨",
    "9": "٩",
  };`

Those arabic letters might have look same but have different code units.

**Comment by Romm01** [comment]
Exactly,
Thank you dear friend
May allah rewards you all,

Could you please tell me how to make Quran page by page through your
package ?

**Comment by aqeelshamz** [comment]
You can utilize these functions for making page by page Quran:

- getPageData(int pageNumber) - Takes [pageNumber] and returns a list containing Surahs and the starting and ending Verse numbers in that page
- getPageNumber(int surahNumber, int verseNumber) - Takes [surahNumber], [verseNumber] and returns the page number of the Quran
- getSurahCountByPage(int pageNumber) - Takes [pageNumber] and returns total surahs count in that page
- getSurahPages(int surahNumber) - Takes [surahNumber] and returns the list of page numbers of that surah
- getVerseCountByPage(int pageNumber) - Takes [pageNumber] and returns total verses count in that page
- getVersesTextByPage(int pageNumber, {bool verseEndSymbol, SurahSeperator surahSeperator, customSurahSeperator}) - Takes [pageNumber], [verseEndSymbol], [surahSeperator] & [customSurahSeperator] and returns the list of verses in that page
