### ISSUE TITLE
verseEndSymbol in MacOS

### ISSUE THREAD

**Issue by zaiehilmi** [aqeelshamz/quran#39]
Assalamualaikum 🙆

Thank you for building this package. It is super helpful for me.

The issue i wanted to highlight is about the verseEndSymbol numbering is not inside the circle (i dont know what is it called).

let me know if Im implemented it wrong or need some more information.

![Tangkapan Skrin 2024-04-12 pada 17 05 42](https://github.com/aqeelshamz/quran/assets/57740351/90407fa7-6164-4344-97a6-a13d507a9b60)

**Comment by aqeelshamz** [comment]
Try to use a different font.
