### ISSUE TITLE
There are many incorrect verses in the 'quran' package. The Arabic script is wrong. Avoid using this package

### ISSUE THREAD

**Issue by Its-NK** [aqeelshamz/quran#44]
There are many incorrect verses in the 'quran' package. The Arabic script is wrong. Avoid using this package.

Here is just few examples and it's just the start

![1](https://github.com/aqeelshamz/quran/assets/90307431/462cac7f-d1ea-4c0f-9877-76d4dbd378b2)
![Correct one](https://github.com/aqeelshamz/quran/assets/90307431/5fa2c8ae-2526-4fe2-8a1a-717ce8966580)
![2](https://github.com/aqeelshamz/quran/assets/90307431/dd917a40-54bf-408c-8b71-c9907b4ac526)
![3](https://github.com/aqeelshamz/quran/assets/90307431/a5891934-5840-458e-83a1-828d3dd8db46)
![4](https://github.com/aqeelshamz/quran/assets/90307431/285a52a4-64e6-40bf-9ced-23d7987aff54)

**Comment by aqeelshamz** [comment]
Nothing wrong.

**Comment by Its-NK** [comment]
How do u see this as "Nothing wrong". I have posted the screen shots from my app, where I used this package to get the quraan. even a blind can see the mistakes in it. How it's "nothing wrong"??????????

**Comment by Madiha-Faisal** [comment]
Yes there are many mistakes in this package. It is not useful ❌

> Nothing wrong.

It is totally wrong

**Comment by sdkysfzai** [comment]
> Nothing wrong.

There are mistakes. Either fix the issues or remove it. We are going to raise awareness against this package anyway

**Comment by aqeelshamz** [comment]
It's problem with the font you are using. Try to use a different font like "Amiri Quran" for example:

![Screenshot 2024-06-13 at 1 15 18 PM](https://github.com/aqeelshamz/quran/assets/69390743/a77b5715-b69e-4971-9d2f-3e03c94966d3)

**Comment by aqeelshamz** [comment]
You could've pointed out the issue in detail. Took some time to find out the issue (بِّ - punctuation kether below shadd). Jazakallah khairan. will add documentation for font setup.
