### ISSUE TITLE
Correct the issue and errors ASAP

### ISSUE THREAD

**Issue by mdsrkhnafd** [aqeelshamz/quran#45]
There are many incorrect verses in the 'quran' package. The Arabic script is wrong. Avoid using this package. Please resolve that issue and bugs ASAP

**Comment by aqeelshamz** [comment]
Please point out the issues in details so that I can fix.

**Comment by mdsrkhnafd** [comment]
See the issue and resolve there are many mistakes. and One Advice Dont Create this type of packages before read The Holy Quran
![WhatsApp Image 2024-06-13 at 10 39 23 AM](https://github.com/aqeelshamz/quran/assets/72373676/07999a12-74a2-485b-bb14-ba7cc7481908)
![WhatsApp Image 2024-06-13 at 10 39 24 AM](https://github.com/aqeelshamz/quran/assets/72373676/ca545d9f-e21a-4773-84e5-d06acbd30383)
![WhatsApp Image 2024-06-13 at 10 39 25 AM (1)](https://github.com/aqeelshamz/quran/assets/72373676/315b4fa8-2009-49f0-ac8f-891986c27735)
![WhatsApp Image 2024-06-13 at 10 39 25 AM](https://github.com/aqeelshamz/quran/assets/72373676/4cb0c25d-d266-46f5-9dcc-4b08d25054c9)

**Comment by mdsrkhnafd** [comment]
see the error and issues. One Advice dont create this type of packages
before reading the Holy Quran

**Comment by aqeelshamz** [comment]
It's a problem with font. Try to use a different font like "Amiri Quran" for example:

![Screenshot 2024-06-13 at 1 13 48 PM](https://github.com/aqeelshamz/quran/assets/69390743/6b9c1154-325f-4534-84e2-100da64cf18a)

**Comment by aqeelshamz** [comment]
Added documentation for Font setup. (v1.2.9)

Jazakallah Khairan
