### ISSUE TITLE
the verse number is not inside the symbol Please Kindely Fix IT 

### ISSUE THREAD

**Issue by SpicierEwe** [aqeelshamz/quran#5]
![Screenshot_20220209-104433](https://user-images.githubusercontent.com/83544142/153126588-ae7846be-2cd2-48b9-a9e7-d96e9d80b26e.png)

**Comment by aqeelshamz** [comment]
Try using the default system font for the verse end symbol. Btw, which platform are you working on?

**Comment by SpicierEwe** [comment]
Assalamualaikum warahmatullahi wabarakatuhu

Im using flutter and dart .
Will try ma beloved brother.

**Comment by SpicierEwe** [comment]
TextSpan(
  text:
      getVerseEndSymbol(
          index +
              1), still not working it was working few days ago but
when i opened it today it wasn't working correctly
  style: TextStyle(
    fontSize: 21,
    color: themeProvider
        .arabicFontColor,
  ),
)

**Comment by SpicierEwe** [comment]
in quran.dart
the error is because of
  arabicNumeric += "\u06dd";

changing it to
"\u06dd" += arabicNumber
did the trick i.e it fixed it .

**Comment by aqeelshamz** [comment]
Ok. Jazakallahu khairan. I will fix it. Or can you make a pull request?

**Comment by SpicierEwe** [comment]
> Ok. Jazakallahu khairan. I will fix it. Or can you make a pull request?

sure

**Comment by aqeelshamz** [comment]
Jazakallahu khairan
