### ISSUE TITLE
Wrong end values in getPageData

### ISSUE THREAD

**Issue by AliYousef97** [aqeelshamz/quran#8]
The method getPageDate return wrong end values.
Wrong usecase: pageNumber = 458

![bug](https://user-images.githubusercontent.com/44493795/154734217-3592c3c2-767e-40be-941b-988b9f5e6cda.PNG)
 
End values should be [88, 5] respectively.

**Comment by aqeelshamz** [comment]
Yes. pageData has bugs in it. Will fix it soon. In Sha Allah.

**Comment by AliYousef97** [comment]
> 

Thanks

**Comment by psyonixFx** [comment]
I'm working on pr for this but then in the middle of testing it just hit me, I don't know wich eddition of Quran you are using 😅

@aqeelshamz  can you please tell me which edition you made the pages data upon ?

**Comment by aqeelshamz** [comment]
Usmani. 604 pages.

**Comment by aqeelshamz** [comment]
Fixed. Jazakallahu khairan ✨
